# test_run.py — Generates historical reports from mock ServiceNow data
#
# PHILOSOPHY: Historical reports are generated by running the REAL pipeline
# (change_miner → ci_mapper → env_classifier → impact_graph) against mock data.
# Only impact_analyzer (LLM) is bypassed — replaced with pre-written mock impact
# that matches what Gemini would say. This means:
#   - Report structure is IDENTICAL to live pipeline output
#   - Historical RAG search returns meaningful, consistent results
#   - No LLM quota is burned generating historical data
#   - Delete reports/ and re-run this script any time to refresh

import os, json
from datetime import datetime
from core.change_miner   import fetch_change
from core.ci_mapper      import map_impacted_cis
from core.env_classifier import classify_environments
from core.impact_graph   import build_impact_graph

# ── Pre-written mock impact blocks ────────────────────────────────────────────
# These mirror what Gemini would return for each CHG.
# Keyed by CHG number.
MOCK_IMPACTS = {

    "CHG0001001": {
        "severity": "HIGH",
        "estimated_downtime_minutes": 120,
        "rollback_complexity": "MEDIUM",
        "affected_business_services": ["RSP"],
        "risk_summary": (
            "Oracle DB quarterly security patch on RSP PROD database (oracle-prd-01). "
            "RSP application servers app-prd-01 and app-prd-02 will lose DB connectivity "
            "for up to 2 hours. DR replica oracle-dr-01 not patched in this window."
        ),
        "potential_failures": [
            "RSP app loses DB connection causing transaction failures",
            "Patch rollback needed if OPatch fails mid-apply",
            "DR replication lag during patch window",
        ],
        "recommendations": [
            "Pre-notify RSP application team 24hrs before window",
            "Verify DR is in sync before patching",
            "Have DBA on standby with rollback script ready",
            "Test RSP connectivity immediately after patch completes",
        ],
    },

    "CHG0001002": {
        "severity": "MEDIUM",
        "estimated_downtime_minutes": 0,
        "rollback_complexity": "LOW",
        "affected_business_services": ["Network Infrastructure"],
        "risk_summary": (
            "Firewall rule update for payment gateway on fw-prd-core-01. "
            "No downtime expected. New IP range 203.0.113.0/24 added, deprecated rules removed. "
            "UK-Axiom and RSP traffic flows through this firewall."
        ),
        "potential_failures": [
            "Misconfigured rule blocking RSP or UK-Axiom traffic",
            "Port conflict with existing payment processor rules",
        ],
        "recommendations": [
            "Test connectivity from RSP and UK-Axiom after rule change",
            "Keep rollback rule in clipboard during change window",
            "Monitor network traffic for 30 min post-change",
        ],
    },

    "CHG0001003": {
        "severity": "LOW",
        "estimated_downtime_minutes": 0,
        "rollback_complexity": "LOW",
        "affected_business_services": ["UK-Axiom"],
        "risk_summary": (
            "Zero-downtime blue-green deployment of UK-Axiom customer portal API v2.4.1. "
            "New JWT refresh endpoint and session timeout fix. "
            "web-prd-01 (UK-Axiom front-end) briefly routes to new version during cutover."
        ),
        "potential_failures": [
            "JWT token incompatibility if old sessions don't refresh",
            "Blue-green cutover causes brief connection reset for active users",
        ],
        "recommendations": [
            "Monitor UK-Axiom login success rate for 1 hour post-deploy",
            "Keep previous version container running for 2 hours as fallback",
        ],
    },

    "CHG0001004": {
        "severity": "LOW",
        "estimated_downtime_minutes": 0,
        "rollback_complexity": "LOW",
        "affected_business_services": ["Storage"],
        "risk_summary": (
            "DR site SAN expansion on san-dr-01. Impact limited to DR only. "
            "No production impact. RSP DR replica oracle-dr-01 I/O may briefly pause "
            "while LUNs are extended."
        ),
        "potential_failures": [
            "DR replication brief pause during LUN extension",
            "SAN firmware issue requiring emergency rollback",
        ],
        "recommendations": [
            "Verify DR replication resumes within 10 min after LUN extension",
            "Alert RSP DBA team before starting",
        ],
    },

    "CHG0001005": {
        "severity": "LOW",
        "estimated_downtime_minutes": 180,
        "rollback_complexity": "LOW",
        "affected_business_services": ["Dev/QA Platform"],
        "risk_summary": (
            "Kubernetes QA cluster upgrade 1.28 → 1.30 on k8s-qa-cluster-01. "
            "All QA workloads offline ~3 hours. Zero production impact. "
            "No RSP, UK-Axiom, SRC, CAD JP or RCL PROD/DR CIs affected."
        ),
        "potential_failures": [
            "Pod incompatibility with K8s 1.30 API changes",
            "Node OS patch requiring extended reboot",
        ],
        "recommendations": [
            "Notify all QA teams of 3-hour outage",
            "Test all QA workloads post-upgrade before sign-off",
        ],
    },

    "CHG0003774804": {
        "severity": "MEDIUM",
        "estimated_downtime_minutes": 30,
        "rollback_complexity": "LOW",
        "affected_business_services": [
            "RSP", "UK-Axiom", "SRC", "CAD JP", "RCL",
            "Global Trading Platform", "Risk Management", "Regulatory Reporting",
            "Core Banking Europe", "APAC Trading Platform", "APAC Risk Management",
            "Americas Trading Platform", "Americas Risk Management", "India Core Banking",
        ],
        "risk_summary": (
            "ExaCC PRD→DR switchover across 5 global data centres using proven Oracle Data Guard "
            "DGMGRL commands. Max 30 min DB downtime per region. "
            "RSP (UK CDC→WDC), UK-Axiom (CDC→WDC), SRC (9TS→DSJ), "
            "CAD JP (2PK→CORP), RCL (BKC→Tata). "
            "Low risk — standard rehearsed procedure."
        ),
        "potential_failures": [
            "Network latency spike between source and target DC during switchover",
            "Redo log gap if replication lag > threshold at switchover time",
            "RSP/UK-Axiom app reconnection failure if connection pool not drained",
            "SRC or CAD JP APAC session loss during 9TS→DSJ or 2PK→CORP switchover",
        ],
        "recommendations": [
            "Verify DG sync (< 5 min lag) before each regional switchover",
            "Pre-notify RSP, UK-Axiom, SRC, CAD JP, RCL app teams of 30 min DB downtime",
            "DBA lead Sanchit Saumay on bridge call throughout window",
            "Contact: Exacc_patching_group@list.db.com for issues",
        ],
    },

    "CHG0003774900": {
        "severity": "LOW",
        "estimated_downtime_minutes": 0,
        "rollback_complexity": "LOW",
        "affected_business_services": [
            "RSP", "UK-Axiom", "Global Trading Platform", "Risk Management",
        ],
        "risk_summary": (
            "ExaCC infra patching UK CDC and Germany DCN post-switchover. "
            "RSP and UK-Axiom already running from WDC/DCB DR nodes — zero app impact. "
            "Patching idle PRD nodes only."
        ),
        "potential_failures": [
            "GI patch failure requiring node restart beyond window",
            "Replication not resuming cleanly after patching",
        ],
        "recommendations": [
            "Confirm RSP and UK-Axiom are serving from WDC/DCB before starting",
            "Do not switchback until all patching verified complete",
        ],
    },

    "CHG0003775100": {
        "severity": "MEDIUM",
        "estimated_downtime_minutes": 30,
        "rollback_complexity": "LOW",
        "affected_business_services": [
            "RSP", "UK-Axiom", "SRC", "CAD JP", "RCL",
            "Global Trading Platform", "APAC Trading Platform",
            "Americas Trading Platform", "India Core Banking",
        ],
        "risk_summary": (
            "ExaCC DR→PRD switchback after patching. Restores RSP, UK-Axiom, SRC, "
            "CAD JP, RCL to original PRD data centres. Max 30 min DB downtime per region. "
            "Lower risk than initial switchover — patched PRD nodes already verified."
        ),
        "potential_failures": [
            "Redo log gap if replication not fully in sync after patching",
            "Application reconnection delay for RSP/UK-Axiom",
        ],
        "recommendations": [
            "Verify DG sync before each regional switchback",
            "Execute in same order as switchovers: IN, SG, DE, UK, NY",
        ],
    },

    "CHG0003776200": {
        "severity": "HIGH",
        "estimated_downtime_minutes": 25,
        "rollback_complexity": "MEDIUM",
        "affected_business_services": [
            "SRC", "CAD JP", "APAC Trading Platform", "APAC Risk Management",
        ],
        "risk_summary": (
            "Unplanned Singapore ExaCC emergency failover (9TS→DSJ) due to storage controller "
            "firmware bug. SRC and CAD JP APAC instances offline 15-30 min. "
            "DGMGRL switchover in progress. SGX trading session may be impacted."
        ),
        "potential_failures": [
            "Data loss if redo log gap at time of storage failure",
            "DSJ capacity insufficient for full PRD workload",
            "SRC collateral calculations delayed during failover",
        ],
        "recommendations": [
            "Immediate: Execute DGMGRL switchover to DSJ",
            "Notify SRC and CAD JP application teams immediately",
            "Raise Oracle SR for ExaCC X9M firmware bug",
            "Do NOT switchback until 9TS storage controller replaced",
        ],
    },

    "CHG0003778500": {
        "severity": "MEDIUM",
        "estimated_downtime_minutes": 30,
        "rollback_complexity": "LOW",
        "affected_business_services": [
            "RSP", "UK-Axiom", "SRC", "CAD JP", "RCL",
            "Global Trading Platform", "Risk Management", "Core Banking Europe",
            "APAC Trading Platform", "APAC Risk Management",
            "Americas Trading Platform", "Americas Risk Management",
            "India Core Banking", "India Payments",
        ],
        "risk_summary": (
            "Full quarterly ExaCC maintenance — 6-week rolling program across all 5 regions. "
            "All applications (RSP, UK-Axiom, SRC, CAD JP, RCL) will experience one 30-min DB "
            "downtime window during their region's switchover week. "
            "GI upgrade 19.22→19.23 and firmware update are well-tested."
        ),
        "potential_failures": [
            "GI upgrade rollback in one region delays entire program",
            "Firmware update failure requiring Oracle hardware support",
            "Schedule slip if any region overruns its window",
        ],
        "recommendations": [
            "Run India (RCL) first as pilot week",
            "Weekly bridge call with all regional DBA leads",
            "Application teams pre-notified per-region switchover date",
            "Full sign-off from global.database@db.com before each week",
        ],
    },
}


def build_report(chg_number: str) -> dict:
    """
    Build a report using the real pipeline steps 1-4, then inject
    the pre-written mock impact (step 5) to avoid LLM quota usage.
    Output structure is IDENTICAL to a live pipeline report.
    """
    print(f"\n  Building: {chg_number}")

    # Steps 1-4: real pipeline — no LLM
    change_data = fetch_change(chg_number)
    primary_ci  = change_data.get("primary_ci_id", "")

    if not primary_ci:
        print(f"  [SKIP] No primary CI for {chg_number}")
        return {}

    all_cis    = map_impacted_cis(primary_ci)
    classified = classify_environments(all_cis)
    graph      = build_impact_graph(all_cis)

    # Step 5: inject pre-written impact (no LLM call)
    impact = MOCK_IMPACTS.get(chg_number, {
        "severity": "MEDIUM",
        "estimated_downtime_minutes": 30,
        "rollback_complexity": "MEDIUM",
        "affected_business_services": [],
        "risk_summary": f"Pre-generated report for {chg_number}.",
        "potential_failures": [],
        "recommendations": [],
    })

    s = classified["summary"]
    print(f"  ✓ PROD={s['PROD']} DR={s['DR']} NonProd={s['NON-PROD']} "
          f"| Severity={impact['severity']}")

    return {
        "meta": {
            "chg_number":  chg_number,
            "analyzed_at": datetime.now().isoformat(),
            "elapsed_sec": 0,
            "source":      "test_run — mock historical data",
        },
        "change":     change_data,
        "ci_summary": classified["summary"],
        "ci_details": {
            "prod":    classified["prod"],
            "dr":      classified["dr"],
            "nonprod": classified["nonprod"],
            "unknown": classified["unknown"],
        },
        "graph":  graph,
        "impact": impact,
    }


def save_report(report: dict) -> str:
    os.makedirs("reports", exist_ok=True)
    chg  = report["meta"]["chg_number"]
    ts   = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = f"reports/report_{chg}_{ts}.json"
    with open(path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    print(f"  [saved] {path}")
    return path


# ── All CHG numbers to generate (matches MockServiceNowData.CHANGES) ──────────
ALL_CHGS = [
    "CHG0001001",    # Oracle DB patch          — RSP PROD
    "CHG0001002",    # Firewall rule update      — Network
    "CHG0001003",    # UK-Axiom API deploy       — UK-Axiom
    "CHG0001004",    # DR SAN expansion          — Storage
    "CHG0001005",    # K8s QA upgrade            — Non-Prod
    "CHG0003774804", # ExaCC PRD→DR switchover   — All 5 apps
    "CHG0003774900", # ExaCC infra patching       — RSP, UK-Axiom
    "CHG0003775100", # ExaCC DR→PRD switchback   — All 5 apps
    "CHG0003776200", # Singapore emergency FO    — SRC, CAD JP
    "CHG0003778500", # Full quarterly maintenance — All 5 apps
]


if __name__ == "__main__":
    print("\n" + "="*60)
    print("  FlowMaster — Generating historical reports from mock data")
    print("="*60)

    # Clear old reports so we don't accumulate stale data
    import shutil
    if os.path.exists("reports"):
        shutil.rmtree("reports")
        print("\n  [cleared] Old reports/ folder deleted")

    # Build and save all reports
    print("\nStep 1: Building reports (pipeline steps 1-4, no LLM)...")
    reports = []
    for chg in ALL_CHGS:
        report = build_report(chg)
        if report:
            save_report(report)
            reports.append(report)

    # Ingest into FAISS RAG
    print(f"\nStep 2: Ingesting {len(reports)} reports into FAISS RAG...")
    print("  (Requires GEMINI_API_KEY for embeddings)\n")
    rag_ok = False
    try:
        from rag.easy_rag import EasyRAG
        rag = EasyRAG()
        for r in reports:
            rag.ingest(r)
            print(f"  [indexed] {r['meta']['chg_number']}")
        stats  = rag.get_stats()
        rag_ok = True
        print(f"\n  RAG index: {stats.get('indexed_changes', len(reports))} vectors ready")
    except Exception as e:
        print(f"\n  [WARNING] RAG skipped: {e}")
        print("  Reports saved to disk — RAG will index on first app.py startup")

    rag_status = "READY" if rag_ok else "SKIPPED (run again with GEMINI_API_KEY set)"
    print(f"""
╔══════════════════════════════════════════════════════════════╗
║         FlowMaster historical data generation complete       ║
╠══════════════════════════════════════════════════════════════╣
║  Reports built  : {len(reports):<42}║
║  RAG ingestion  : {rag_status:<42}║
╠══════════════════════════════════════════════════════════════╣
║  CHGs covered:                                               ║
║  CHG0001001  Oracle DB patch          RSP PROD               ║
║  CHG0001002  Firewall rule update     Network                ║
║  CHG0001003  UK-Axiom API deploy      UK-Axiom               ║
║  CHG0001004  DR SAN expansion         Storage/RSP DR         ║
║  CHG0001005  K8s QA upgrade           Non-Prod only          ║
║  CHG0003774804 ExaCC PRD→DR          All 5 apps (30min)     ║
║  CHG0003774900 ExaCC Infra Patch     RSP, UK-Axiom (0min)   ║
║  CHG0003775100 ExaCC DR→PRD          All 5 apps (30min)     ║
║  CHG0003776200 SG Emergency FO       SRC, CAD JP (HIGH)     ║
║  CHG0003778500 Full Quarterly        All 5 apps (6 weeks)   ║
╠══════════════════════════════════════════════════════════════╣
║  Next: streamlit run app.py                                  ║
║  Try: CHG0003774804 → ask "show similar past changes"        ║
╚══════════════════════════════════════════════════════════════╝
""")